- name: Detect SSH Port
  include: detect_port.yaml

- name: Trust Host Key
  include: hostkey.yaml

# Gather facts should be set to false when running this role since it will
# fail if the Ansible SSH port is not set correctly.
# We run setup to gather facts here once the SSH port is set up.
- name: Run deferred setup to gather facts
  setup:
  when: not skip_facts